apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer # This type exposes the service outside the cluster
  selector:
    app: forum-app # Selects Pods with the 'app: forum-app' label
  ports:
    - protocol: TCP
      port: 3000 # The port the service will be exposed on
      targetPort: 3000 # The port on the pod to forward to