apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data # The name for our data claim
spec:
  accessModes:
    - ReadWriteOnce # This volume can be mounted by one node at a time
  resources:
    requests:
      storage: 1Gi # Request 1 Gigabyte of storage